use_frameworks!

platform :ios, '12.0'

target 'CirclePay_Pod_iOS_Example' do
  pod 'CirclePay_Pod_iOS', :path => '../'
  pod 'Alamofire', '5.4.1'
  pod "FontBlaster" , '5.3.0'
  pod 'IQKeyboardManagerSwift', '6.5.0'
  target 'CirclePay_Pod_iOS_Tests' do
    inherit! :search_paths

    
  end
end
