use_frameworks!

platform :ios, '12.0'

target 'CirclePay_Pod_iOS_Example' do
  pod 'CirclePay_Pod_iOS', :path => '../'
  pod 'Alamofire', '5.4.1'
  pod "FontBlaster" , '5.3.0'
  pod 'IQKeyboardManagerSwift', '6.5.0'
  pod 'Kingfisher', '~> 7.2.2'
  
  target 'CirclePay_Pod_iOS_Tests' do
    inherit! :search_paths
    pod 'OHHTTPStubs/Swift' , '~> 9.1.0'
    
  end
end
