use_frameworks!

platform :ios, '9.0'

target 'CirclePay_Pod_iOS_Example' do
  pod 'CirclePay_Pod_iOS', :path => '../'

  target 'CirclePay_Pod_iOS_Tests' do
    inherit! :search_paths

    
  end
end
